version: '3.9'

services:
  testdb:
    image: postgres
    ports:
      - '5432'
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    networks:
      - testapi
  testrunner:
    build:
      context: ./
      dockerfile: Dockerfile.test
    ports:
      - '5000'
    environment:
      - PORT=5000
      - HOST="0.0.0.0"
      - DATABASE_URL=postgres://postgres:postgres@testdb:5432/postgres?schema=public
    volumes:
      - ./:/usr/src/app
      - /usr/src/app/node_modules
    depends_on:
      - testdb
    networks:
      - testapi
    entrypoint: ['/bin/sh', '-c']
    command:
      - ./wait-for-it.sh testdb:5432 -- ./test.sh
networks:
  testapi:
