version: '3.9'

services:
  db:
    image: postgres
    ports: [5432:5432]
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    networks:
      - api
  api:
    build:
      context: ./
      dockerfile: Dockerfile.dev
    depends_on:
      - db
    ports:
      - '5000:5000'
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    networks:
      - api
    environment:
      - PORT=5000
      - HOST=0.0.0.0
      - DATABASE_URL="postgres://postgres:postgres@db:5432/postgres?schema=public"
networks:
  api:
